test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials.aws[:access_key_id] %>
  secret_access_key: <%= Rails.application.credentials.aws[:secret_access_key] %>
  region: <%= Rails.application.credentials.aws[:region] %>
  bucket: <%= Rails.application.credentials.aws[:bucket] %>

amazon_prod:
  service: S3
  access_key_id: <%= Rails.application.credentials.aws_prod[:access_key_id] %>
  secret_access_key: <%= Rails.application.credentials.aws_prod[:secret_access_key] %>
  region: <%= Rails.application.credentials.aws_prod[:region] %>
  bucket: <%= Rails.application.credentials.aws_prod[:bucket] %>
